### ISSUE TITLE
[BUG]Both pipenv and virtualenv/pip is being used

### ISSUE THREAD

**Issue by grapheo12** [iit-technology-ambit/Syphus#23]
## Detailed Description

Project structure contains both ```requirements.txt``` and ```Pipfile```. As we are using pipenv, the former should there be no longer.

## Possible Solution

Delete ```requirements.txt``` and change Travis CI setup.
Follow [this link](https://jollyremedy.wordpress.com/2018/02/07/using-pipenv-in-a-travis-build/) for reference.
Also change the "Adding dependencies" part of README.md

**Comment by thealphadollar** [comment]
I don't think this should be done until we are entirely setup since a few programs don't support pipenv as of now and we don't want to limit ourselves.

**Comment by thealphadollar** [comment]
@iit-technology-ambit/developers We will always be using both. `requirements.txt` is required for the backend while Pipfile makes it easy for development purposes.
